import type { Metadata } from 'next'
import {  Hanken_Grotesk } from 'next/font/google'
import './globals.css'
import ContextProvider from '@/context/main-context'

const  hankenGrotesk =  Hanken_Grotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Digital ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-primary1 md:pt-36 pt-20 ${hankenGrotesk.className}`}>
        <ContextProvider>
          {children}
          <div className="blur1 left-0 top-10   " />
          <div className="blur2 right-0 top-10   " />
        </ContextProvider>
      </body>
    </html>
  );
}
